/** @type {Partial<import("typedoc").TypeDocOptions>} */
const config = {
	alwaysCreateEntryPointModule: false,
    entryPoints: [
		'./base/state/hooks.ts', './base/methods.ts', './base/merged-state.ts',
		'./classy/class/index.ts', './classy/instance/index.ts', './classy/logic/index.ts',
		'helpers',
	],
    out: 'docs',
	entryPointStrategy: 'resolve', // 'expand',
	plugin: [
		// 'typedoc-plugin-markdown',
		// '@shipgirl/typedoc-plugin-versions',
		// '@8hobbies/typedoc-plugin-404',
		// 'typedoc-plugin-include-example',
		// 'typedoc-plugin-redirect',
		'typedoc-plugin-mdn-links',
		'typedoc-plugin-coverage',
	],
    excludeNotDocumented: true,
    // "excludeNotDocumentedKinds": ["Property", "Interface", "TypeAlias"]
	// externalPattern: 'standalone-docs/**/*.md',
	exclude: "**/internal/**/*",
	projectDocuments: ["standalone-docs/discussion/index.md"],
	excludeInternal: true, // Use @internal doc tag.
	name: 'Oore',
	includeVersion: true,
	disableSources: true,
	groupReferencesByType: true,
    "navigation": {
        "includeCategories": true,
        "includeGroups": true,
        "includeFolders": false,
        "compactFolders": false,
        "excludeReferences": false,
    },
	categorizeByGroup: false,
	// defaultCategory: "Category Name",
	// categoryOrder: ["Category Name", "Other Category", "*"],
	// groupOrder: ["Variables", "Functions", "*"],
	sort: [
		// "source-order",
		// "alphabetical",
		// "alphabetical-ignoring-documents",
		// "enum-value-ascending",
		// "enum-value-descending",
		// "enum-member-source-order",
		"static-first",
		// "instance-first",
		// "visibility",
		// "required-first",
		// "kind",
		"external-last",
		// "documents-first",
		"documents-last",
	],
	// sortEntryPoints: false,
    kindSortOrder: [
        "Reference",
        "Project",
        "Module",
        "Namespace",
        "Enum",
        "EnumMember",
        "Class",
        "Interface",
        "TypeAlias",
        "Constructor",
        "Property",
        "Variable",
        "Function",
        "Accessor",
        "Method",
        "Parameter",
        "TypeParameter",
        "TypeLiteral",
        "CallSignature",
        "ConstructorSignature",
        "IndexSignature",
        "GetSignature",
        "SetSignature",
    ],
	highlightLanguages: ['jsx', 'tsx', 'ts', 'js', 'css', 'scss', 'html'],
};

export default config;
